---
# See http://doc.silverstripe.org/framework/en/topics/configuration
# Caution: Indentation through two spaces, not tabs
Name: mysite
After: 'framework/*','cms/*'
---
SSViewer:
  source_file_comments: true
  theme_enabled: false
MySQLDatabase:
  connection_charset: 'utf8'
GDBackend:
  default_quality: 100
SiteTree:
  nested_urls: true
  # create_default_pages: false
Email:
  admin_email: 'myEmail@mysite.com'
OpenGraph:
  application_id: 'SiteConfig'  # Or set the application id
  admin_id: 'SiteConfig'        # Or set the admin id
  default_locale: 'nl_NL'
  default_tagbuilder: 'OpenGraphBuilder'
ShareCare:
  twitter_username: 'your-username'

SiteConfig:
  extensions:
    - 'mysiteSiteConfigExtension'
LeftAndMain:
  extra_requirements_css:
    - 'mysite/css/cms.css'
  extensions:
    - 'mysiteLeftAndMainExtension'
